### ISSUE TITLE
Firefox Extension Causes Choppy / Slow Scrolling

### ISSUE THREAD

**Issue by Noah-Huppert** [sourcegraph/sourcegraph-browser-extensions#23]
# Behavior
The SourceGraph Firefox extension causes scrolling on file view pages of GitHub.com to become very slow and choppy. 

[Video](https://photos.app.goo.gl/6bS393tTTfo9h91c6)

# Steps To Reproduce
1. Use Firefox
2. Have the SourceGraph extension installed
3. View a source file on GitHub.com ([ex](https://github.com/gsuitedevs/go-samples/blob/4691b5efe493c315c0d8339563ad1ebebbeaa839/sheets/quickstart/quickstart.go))
4. Scroll up or down
5. Notice how the scrolling lags quite a bit
6. Disable the SourceGraph extension
7. Reload GitHub.com page
8. Notice how scrolling is smooth as butter

# System Information
**OS:** `4.15.14-1-ARCH #1 SMP PREEMPT Wed Mar 28 17:34:29 UTC 2018 x86_64 GNU/Linux`
**Browser:** Firefox 59.0.2 (64-bit)  
**Extension Version:** SourceGraph for Firefox 1.7.14

**Comment by hoegaarden** [comment]
For me the same happens, but only if I have the [widecreen github](https://userstyles.org/styles/124318/widescreen-github) theme enabled. Maybe that helps in tracking down the issue.

**Comment by KattMingMing** [comment]
@hoegaarden Thank you for reporting you're still seeing this issue. Could you link to a page that reproduces the issue? (I will also install the widescreen GitHub theme).

@Noah-Huppert are you still seeing this issue on the file linked in the original ticket? Are you using any other Firefox Addons?

**Comment by hoegaarden** [comment]
@KattMingMing I can see it pretty much on any GH page. Just tested on this one: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/types.go

When the widescreen theme is enabled, scrolling is barely working. If the theme is disabled, scrolling works again as it should.

**Comment by KattMingMing** [comment]
@hoegaarden - Could you provide the extension version, Firefox version, and OS specs?

**Comment by KattMingMing** [comment]
@hoegaarden - I've pushed a new version of the extension 1.7.24 that includes a fix for the choppy scrolling. Once you're on 1.7.24 could you verify that you're no longer seeing this issue?

**Comment by Noah-Huppert** [comment]
@KattMingMing I have tons of other Firefox addons, I believe the only other one that injects content into the page is ZenHub.

I will check to see if I am still encountering this issue on the new version.

**Comment by hoegaarden** [comment]
@KattMingMing -- 1.7.24 seems to be way better!

**Comment by KattMingMing** [comment]
Great! Will close this issue. Thanks again for reporting and let us know if you have any additional feedback!
